---
title: "cleaned_data"
output: github_document
---

load packages
```{r}
library(tidyverse)
```

Here I will clean the 2019_subway_rider_data 

```{r}
subway_rider_data = 
  read_csv("data/2019_subway_rider_data.csv") |> 
  janitor::clean_names()


subway_drops =
  subway_rider_data |> 
  select(-survey_stop_borough, -survey_stop_location) |> 
  drop_na() |> 
  mutate(survey_id = row_number()) |> 
  relocate(survey_id, .before = 1)
  
```

Now I will specifically clean the data within the columns

Cleaned rider frequency table: 
```{r}
rider_data =
  subway_drops |>
  mutate(
    use_of_subway_frequency = case_when(
      use_of_subway_frequency == "Everyday / Almost everyday" ~ "Every day",
      use_of_subway_frequency == "More than once a week, varies" ~ "Several times a week",
      use_of_subway_frequency %in% c("Weekdays, Mon - Fri", "~5 days per week") ~ "5 days per week",
      use_of_subway_frequency == "Once a week" ~ "Once a week",
      use_of_subway_frequency == "Once a month" ~ "Once a month",
      use_of_subway_frequency == "Almost never" ~ "Almost never",
      use_of_subway_frequency == "Never" ~ "Never",
      TRUE ~ NA_character_
    ),
    use_of_subway_frequency = 
      factor(
        use_of_subway_frequency,
        levels = c("Never", 
                   "Almost never", 
                   "Once a month", 
                   "Once a week",
                   "Several times a week", 
                   "5 days per week", 
                   "Every day"),
        ordered = TRUE)
    )


rider_data =
  subway_drops |> 
  mutate(average_length_subway_ride = 
           factor(average_length_subway_ride,
                  levels = c("< 20 min", 
                             "20 - 40 min", 
                             "40 - 60 min",
                             "60 - 90 min", 
                             "90 min - 2 hours"),
                  ordered = TRUE))


rider_data =
  subway_drops |>
  mutate(
    overall_satisfaction = 
      recode(
        overall_satisfaction,
        "Not satisfied" = "Unsatisfied"),
    overall_satisfaction = 
      factor(
        overall_satisfaction,
        levels = c("Highly unsatisfied",
                 "Unsatisfied",
                 "Neutral",
                 "Somewhat satisfied",
                 "Very satisfied"),
      ordered = TRUE)
    )


rider_data =
  subway_drops |> 
  mutate(
    frequency_of_delays = factor(
      frequency_of_delays,
      levels = c("Everyday",
                 "A few times a week",
                 "Rarely",
                 "Almost never",
                 "Never"),
      ordered = TRUE)
    )
    
```


converting complaints into long format: 


```{r}
rider_data =
  rider_data |> 
  mutate(
    top_three_complaints = 
      str_remove_all(top_three_complaints, "\\[|\\]|'")
  ) |> 
  separate_rows(top_three_complaints, sep = ",") |> 
  mutate(top_three_complaints = 
           str_trim(top_three_complaints)) |> 
  rename(complaint = top_three_complaints)
```

Making some of the variables as a character and some as a factor!


```{r}
rider_data = 
  rider_data |> 
  mutate(
    is_subway_affordable = if_else(
      is_subway_affordable == "Yes", TRUE, FALSE),
    zip_code = as.character(zip_code)
    )


rider_data =
  rider_data |> 
  mutate(
    across(c(subway_line_used_most_often,
             get_to_subway_via,
             primary_use_of_subway,
             alternative_transport), as.factor)
  )
```



should approximate delay duration be an ordered factor?

anyways final data set is rider_data





